#!/usr/bin/env python3
"""Copy the photo collection into `assets/photos/` with normalised filenames,
and emit `_data/photos.yml` so Jekyll can iterate them.

Each manifest entry looks like:

  - file: aunty-peg-alone.jpg
    slug: aunty-peg-alone
    caption: ""
    story: null         # populated manually to associate with a story
    tale:  null         # or a tale

Curated associations (captions, story/tale links) live in `_data/photo_overrides.yml`
if present, and are merged in so that re-ingestion never clobbers hand work.
"""

from __future__ import annotations

import re
import shutil
import sys
import unicodedata
from pathlib import Path

try:
    import yaml  # PyYAML
except ImportError:
    yaml = None  # We fall back to hand-emitting YAML.

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT.parent / "Women of Cornforth Website Information" / "Women of cornforth Photographs"
DEST_DIR = ROOT / "assets" / "photos"
MANIFEST = ROOT / "_data" / "photos.yml"
OVERRIDES = ROOT / "_data" / "photo_overrides.yml"


def slugify(value: str) -> str:
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    value = re.sub(r"[^\w\s.-]", "", value).strip().lower()
    value = re.sub(r"[\s_]+", "-", value)
    value = re.sub(r"-+", "-", value)
    return value.strip("-")


def normalise(name: str) -> tuple[str, str]:
    """Return (slug, dest_filename) for a source photo filename."""
    stem = Path(name).stem
    suffix = Path(name).suffix.lower()
    # Normalise jpeg → jpg for consistency.
    if suffix in {".jpeg"}:
        suffix = ".jpg"
    slug = slugify(stem)
    return slug, f"{slug}{suffix}"


def load_overrides() -> dict[str, dict]:
    if not OVERRIDES.exists():
        return {}
    if yaml is None:
        print(f"  [warn] PyYAML not available; cannot read {OVERRIDES}")
        return {}
    data = yaml.safe_load(OVERRIDES.read_text(encoding="utf-8")) or {}
    # Expected shape: {slug: {caption: ..., story: ..., tale: ...}}
    return data if isinstance(data, dict) else {}


def emit_yaml(entries: list[dict]) -> str:
    """Emit a minimal, human-friendly YAML list.

    Hand-rolled so we don't take a hard dependency on PyYAML, and so the file
    stays diff-friendly (keys in a stable order, one entry per block).
    """
    lines: list[str] = [
        "# Auto-generated by scripts/ingest_photos.py.",
        "# Curated overrides (captions, story/tale links) live in photo_overrides.yml",
        "# and are merged in on each re-run; do not edit this file directly.",
        "",
    ]
    for e in entries:
        lines.append(f"- file: {e['file']}")
        lines.append(f"  slug: {e['slug']}")
        caption = (e.get("caption") or "").replace('"', "'")
        lines.append(f'  caption: "{caption}"')
        story = e.get("story")
        tale = e.get("tale")
        lines.append(f"  story: {story if story else 'null'}")
        lines.append(f"  tale: {tale if tale else 'null'}")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not SRC_DIR.exists():
        print(f"Photo source not found: {SRC_DIR}", file=sys.stderr)
        return 2

    DEST_DIR.mkdir(parents=True, exist_ok=True)
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)

    overrides = load_overrides()

    # Wipe destination so removed source photos don't linger.
    for existing in DEST_DIR.iterdir():
        if existing.is_file():
            existing.unlink()

    seen: dict[str, Path] = {}
    entries: list[dict] = []
    skipped: list[str] = []

    for src in sorted(SRC_DIR.iterdir()):
        if not src.is_file():
            continue
        if src.suffix.lower() not in {".jpg", ".jpeg", ".png", ".gif"}:
            skipped.append(src.name)
            continue
        slug, fname = normalise(src.name)
        if slug in seen:
            # Collision: append a numeric suffix.
            n = 2
            while f"{slug}-{n}" in seen:
                n += 1
            slug = f"{slug}-{n}"
            fname = f"{slug}{Path(fname).suffix}"
        seen[slug] = src
        shutil.copy2(src, DEST_DIR / fname)

        override = overrides.get(slug, {}) if isinstance(overrides, dict) else {}
        entries.append({
            "file":    fname,
            "slug":    slug,
            "caption": override.get("caption", ""),
            "story":   override.get("story"),
            "tale":    override.get("tale"),
        })

    MANIFEST.write_text(emit_yaml(entries), encoding="utf-8")
    print(f"Copied {len(entries)} photo(s) into {DEST_DIR.relative_to(ROOT)}")
    print(f"Wrote manifest: {MANIFEST.relative_to(ROOT)}")
    if skipped:
        print(f"Skipped non-image files: {', '.join(skipped)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
